apiVersion: v1
kind: Service
metadata:
  name: mariadb-tomer
  namespace: tomer
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mariadb
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-tomer
  namespace: tomer
spec:
  selector:
    matchLabels:
      app: mariadb-tomer
  serviceName: mariadb-tomer
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb-tomer
    spec:
      containers:
        - name: mariadb-tomer
          image: public.ecr.aws/c0m6s3p2/tomer-k8s-inegrative/db:latest
          args:
            - "--default-authentication-plugin=mysql_native_password"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "somewordpress"
            - name: MYSQL_DATABASE
              value: "wordpress"
            - name: MYSQL_USER
              value: "wordpress"
            - name: MYSQL_PASSWORD
              value: "wordpress"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
  # volumeClaimTemplates:
  #   - metadata:
  #       name: tomer-db-vc
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       # storageClassName: ebs-sc-tomer
  #       resources:
  #         requests:
  #           storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: tomer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc-tomer
