controller:
  rbac:
    create: "true"
    scope: "true"
  scope:
    enabled: "true"
    namespace: tomer
  service:
    type: LoadBalancer
  ingressClassResource:
    name: "nginx"
    enabled: "true"
    default: "true"
    controllerValue: "k8s.io/ingress-nginx"
