apiVersion: v1
kind: Service
metadata:
  name: wordpress-tomer
  namespace: tomer
  labels:
    app: wordpress-tomer
spec:
  selector:
    app: wordpress-tomer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim-tomer
  namespace: tomer
spec:
  storageClassName: ebs-sc-tomer
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-tomer
  namespace: tomer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-tomer
  template:
    metadata:
      labels:
        app: wordpress-tomer
    spec:
      containers:
        - name: wordpress-tomer
          image: public.ecr.aws/c0m6s3p2/tomer-k8s-inegrative/wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: "mariadb-tomer"
            - name: WORDPRESS_DB_USER
              value: "wordpress"
            - name: WORDPRESS_DB_PASSWORD
              value: "wordpress"
            - name: WORDPRESS_DB_NAME
              value: "wordpress"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-volume
              mountPath: /var/www/html
      volumes:
        - name: wordpress-volume
          persistentVolumeClaim:
            claimName: wp-pv-claim-tomer
