controller:
  rbac:
    create: "true"
    scope: "true"
  scope:
    enabled: "true"
    namespace: tomer
  service:
    type: LoadBalancer
  ingressClassResource:
    name: tomer-ingress-class
    enabled: "true"
    default: "true"
    controllerValue: "k8s.io/ingress-nginx"

grafana:
  server:
    root_url: "http://aab8b1519715e49cb8ff749459d702cc-1018892589.us-east-1.elb.amazonaws.com/grafana"
    serve_from_sub_path: true
